// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DataBusinessService.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class deleteTableMyEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteTableMyEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201503052038500_deleteTableMyEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
